# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Customer Loyalty &amp; Retention Management Software
email: hello@pegke.com
description: Customer Loyalty &amp; Retention Management Software, integrates with merchant POS systems to give consumers a single identity to earn business-specific rewards
keywords: customer loylaty, loyalty software, retail loyalty program, loyalty program, reward points, customer loylaty program, retention management
productname: Pegke Rewards &#8482;
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pegke.com" # the base hostname & protocol for your site
lighturl: http://lightrains.com
permalink:  :title
lang: en_US

twitter_username: pegkeapp
github_username:  pegkeloyalty
fb_username: pegkeapp
gplus_username: +Pegke
phoneno: +91 (471) 400-0056
phone: 914714000056

cover: /public/og/pegke-og.jpg

dashboard:
  base_url: https://pegke.com/
  api_base: dashboard.pegke.com/v1
  app_down: https://pegke.com/apps

apps:
  android: https://pegke.com/
  apple: https://pegke.com/
  windows: https://pegke.com/
# Build settings
markdown: kramdown
encoding: UTF-8

exclude:
  - bower_components
  - public/imgfull
  - public/cssfull
  - package.json
  - node_modules
  - gulpfile.js
  - .nojekyll

# Custom Settings
mailchimp_url: //pegke.us9.list-manage.com/subscribe/post?u=49c28e4c02bbc2d7dfd64815e&amp;id=20b2bd793b
mailchimp_list_id:  20b2bd793b

gems:
  - jekyll-paginate

paginate: 10
tag_page_dir: tag
tag_feed_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed
